<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * romirami implementation : © Guillaume Benny bennygui@gmail.com
 *
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 */

// Globals
const MARKET_SIZE_NUMBER = 6;
const MARKET_SIZE_CONTRACT = 4;
const MARKET_MAX_NUMBER_CHOICE = 3;
const NB_TROHPY = 4;
const CONTRACT_KIND_COUNTS = [2, 3, 4, 5];
const MIN_HAND_SIZE = 3;
const MAX_HAND_SIZE = 10;
const SUIT_TO_TROPHY = [
    1 => 0,
    2 => 3,
    3 => 1,
    4 => 2,
];
const KIND_TO_TROPHY = [
    2 => 0,
    3 => 1,
    4 => 2,
    5 => 3,
];

// States

const STATE_PRE_CHOOSE_NUMBER_FROM_MARKET = 'STATE_PRE_CHOOSE_NUMBER_FROM_MARKET';
const STATE_PRE_CHOOSE_NUMBER_FROM_MARKET_ID = 1000;
const STATE_CHOOSE_NUMBER_FROM_MARKET = 'STATE_CHOOSE_NUMBER_FROM_MARKET';
const STATE_CHOOSE_NUMBER_FROM_MARKET_ID = 1001;

const STATE_PRE_CHOOSE_CONTRACT_FROM_MARKET = 'STATE_PRE_CHOOSE_CONTRACT_FROM_MARKET';
const STATE_PRE_CHOOSE_CONTRACT_FROM_MARKET_ID = 1002;
const STATE_CHOOSE_CONTRACT_FROM_MARKET = 'STATE_CHOOSE_CONTRACT_FROM_MARKET';
const STATE_CHOOSE_CONTRACT_FROM_MARKET_ID = 1003;

const STATE_REFILL_MARKET = 'STATE_REFILL_MARKET';
const STATE_REFILL_MARKET_ID = 1004;
const STATE_CHOOSE_NUMBER_TO_DISCARD = 'STATE_CHOOSE_NUMBER_TO_DISCARD';
const STATE_CHOOSE_NUMBER_TO_DISCARD_ID = 1005;

const STATE_END_OF_TURN = 'STATE_END_OF_TURN';
const STATE_END_OF_TURN_ID = 1006;
const STATE_PRE_GAME_END = 'STATE_PRE_GAME_END';
const STATE_PRE_GAME_END_ID = 1007;

// Notifications
const NTF_UPDATE_CARDS = 'NTF_UPDATE_CARDS';
const NTF_UPDATE_PUBLIC_COUNTS = 'NTF_UPDATE_PUBLIC_COUNTS';
const NTF_UPDATE_PRIVATE_COUNTS = 'NTF_UPDATE_PRIVATE_COUNTS';
const NTF_UPDATE_JOKER = 'NTF_UPDATE_JOKER';

// Game Options

// User preferences

// Game Statistics
const STATS_TABLE_NB_ROUND = 'STATS_TABLE_NB_ROUND';

const STATS_PLAYER_SCORE_FROM_CONTRACT = 'STATS_PLAYER_SCORE_FROM_CONTRACT';
const STATS_PLAYER_SCORE_FROM_TROPHY = 'STATS_PLAYER_SCORE_FROM_TROPHY';
const STATS_PLAYER_SCORE_FROM_SUIT_BONUS = 'STATS_PLAYER_SCORE_FROM_SUIT_BONUS';
const STATS_PLAYER_SCORE_FROM_STAR = 'STATS_PLAYER_SCORE_FROM_STAR';
const STATS_PLAYER_NB_CONTRACT = 'STATS_PLAYER_NB_CONTRACT';
const STATS_PLAYER_NB_TROPHY = 'STATS_PLAYER_NB_TROPHY';
const STATS_PLAYER_NB_NUMBER_CHOOSE = 'STATS_PLAYER_NB_NUMBER_CHOOSE';
const STATS_PLAYER_NB_NUMBER_DRAW = 'STATS_PLAYER_NB_NUMBER_DRAW';
const STATS_PLAYER_NB_NUMBER_DISCARD = 'STATS_PLAYER_NB_NUMBER_DISCARD';
const STATS_PLAYER_NB_NUMBER_PLAY = 'STATS_PLAYER_NB_NUMBER_PLAY';
const STATS_PLAYER_IS_FIRST_PLAYER = 'STATS_PLAYER_IS_FIRST_PLAYER';
